apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: github-actions-devops
spec:
  selector:
    matchLabels:
      app: github-actions-devops
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: github-actions-devops
    spec:
      containers:
        - name: github-actions-devops
          image: github-actions-devops:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster